name: Dealsync Deal State Sync
on:
  workflow_dispatch:
    inputs:
      offset:
        type: string
        default: '0'
      limit:
        type: string
        default: '500'

jobs:
  create:
    runs-on: ubuntu-latest
    environment: '0x226c2acd33ef649bff3339670b6de489880a094acf7390df6cad4b5e18a17665'
    steps:
      - id: sync-deal-states
        name: Create deal states from email metadata diff
        uses: creatorland/dealsync-action@8776bb64aa49f3f7c22197cc2eb0bcd0dd4214c5
        with:
          command: sync-deal-states
          offset: ${{ inputs.offset }}
          limit: ${{ inputs.limit }}
          auth-url: ${{ secrets.SXT_AUTH_URL }}
          auth-secret: ${{ secrets.SXT_AUTH_SECRET }}
          api-url: ${{ secrets.SXT_API_URL }}
          biscuit: ${{ secrets.SXT_BISCUIT }}
          schema: ${{ secrets.SXT_SCHEMA }}
          rate-limiter-url: ${{ secrets.SXT_RATE_LIMITER_URL }}
          rate-limiter-api-key: ${{ secrets.SXT_RATE_LIMITER_API_KEY }}
