name: ds-sync-deal-values-cb36159
authority: '0x553b60381dC74493d03b2865C818350f3347Ac7f'
on:
  workflow_dispatch:

concurrency:
  group: sync-deal-values-testnet
  cancel-in-progress: false

jobs:
  backfill:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: '0xead32ddc4a0d3f3845531916e59a52cdd21c97a41b7ad2806a0cefac57b402bb'
    steps:
      - id: backfill
        name: Run deal-value backfill
        timeout-minutes: 60
        uses: creatorland/dealsync-action@cb36159
        with:
          command: sync-deal-values
          sxt-auth-url: ${{ secrets.SXT_AUTH_URL }}
          sxt-auth-secret: ${{ secrets.SXT_AUTH_SECRET }}
          sxt-api-url: ${{ secrets.SXT_API_URL }}
          sxt-biscuit: ${{ secrets.SXT_BISCUIT }}
          sxt-schema: ${{ secrets.SXT_SCHEMA }}
          backfill-start-date: '2026-03-31'
          backfill-batch-size: '500'
          backfill-dry-run: 'true'
          db-max-retries: ${{ secrets.DB_MAX_RETRIES }}
